// Generated by CoffeeScript 1.6.1
(function() {
  var T,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  T = require("../TermUI");

  T.CheckBox = (function(_super) {

    __extends(CheckBox, _super);

    function CheckBox() {
      return CheckBox.__super__.constructor.apply(this, arguments);
    }

    return CheckBox;

  })(T.Box);

}).call(this);
